### ISSUE TITLE
[andotp] Unable to import encrypted json

### ISSUE THREAD

**Issue by mannp** [paolostivanin/OTPClient#126] opened 2019-04-09 18:18 UTC
Hi there
Love the app, thanks for creating it.

I am trying to reimport an updated aes file from andOTP and OTPClient just exits with no message.

I have download your debug app and all 3 tests complete successfully from here -> https://github.com/paolostivanin/OTPClient/issues/88

Thanks in advance for any pointers

OTPClient 1.4 (arch) and andOTP 0.6.1

**Comment by paolostivanin** [comment] 2019-04-13 07:52
Hello!
So, if I got it right:
* you exported andOTP db and imported it into OTPclient. This worked :heavy_check_mark: 
* you added/deleted some tokens from andOTP, exported the db and imported it into OTPClient, Nothing changed in OTPClient. Am I right?

**Comment by mannp** [comment] 2019-04-13 09:20
Hi there
Well I wasn't sure how OTPclient handled importing again, as andOTP has a 'replace all' option which I use for updating the other andOTP clients, so for OTPClient I moved the db and created another and tried to import into a clean db.

So the second bullet should read;

you added/deleted some tokens in andOTP, exported the db and imported it into OTPClient, using a new db and Nothing changed in OTPClient. OTPClient exited without importing anything.

**Comment by paolostivanin** [comment] 2019-04-21 07:52
Hello @mannp ,
sorry for the long time it takes me the answer but I'm really busy these days.
I'll try to reproduce it during these holiday days :+1:

**Comment by mannp** [comment] 2019-04-21 12:47
Hi @paolostivanin no problem at all, enjoy your holidays first :+1:

**Comment by paolostivanin** [comment] 2019-04-23 18:57
Hey @mannp , that's what I did:
1. created some tokens in andOTP
2. exported to encrypted json
3. imported into OTPClient
==> all good here
4. deleted token from andOTP
5. added a new token in andOTP
6. exported to encrypted json
7. imported into OTPClient
==> the new token was successfully added
==> the deleted token of course it's not deleted from OTPClient. This must be manually deleted

**Comment by mannp** [comment] 2019-04-24 14:21
Hi @paolostivanin well only that it didn't work for me :-1: 

I am only adding tokens to andOTP rather than deleting but not likely to be an issue.

I previously used your debug app and all was well, so don't know.

**Comment by paolostivanin** [comment] 2019-04-24 14:48
Yes, I use openSUSE Tumbleweed as daily driver.
I'll try some other things tomorrow, let's see...

**Comment by paolostivanin** [comment] 2019-04-29 13:57
@mannp I tried again without luck :disappointed: 
Could you please start `otpclient` from the terminal and see if something is printed there when importing the data?

**Comment by mannp** [comment] 2019-04-29 16:08
@paolostivanin as requested :)

 08:46:34   otpclient
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added
[INFO] Duplicate element not added

(OTPClient:23320): GLib-CRITICAL **: 16:27:43.776: g_strlcat: assertion 'dest != NULL' failed
(OTPClient:23320): GLib-CRITICAL **: 16:27:43.776: g_strlcat: assertion 'dest != NULL' failed
(OTPClient:23320): GLib-CRITICAL **: 16:27:43.776: g_strlcat: assertion 'dest != NULL' failed
(OTPClient:23320): GLib-CRITICAL **: 16:27:43.776: g_strlcat: assertion 'dest != NULL' failed
[1]    23320 segmentation fault (core dumped)  otpclien

**Comment by paolostivanin** [comment] 2019-04-29 16:11
Ah-ha! Now we're talking 👍 
Some questions to better understand your setup:
1. How many tokens are you trying to import?
2. Only totp or also hotp?
3. Do you have steam tokens?
4. Do you have blank label and/or issuer?

**Comment by mannp** [comment] 2019-04-29 16:19
How many tokens are you trying to import? >> 70
    Only totp or also hotp? >> Only totp
    Do you have steam tokens? >> No
    Do you have blank label and/or issuer? >> Maybe, in andotp or when imported into otpclient?

**Comment by paolostivanin** [comment] 2019-04-30 13:25
I added some debugging output in a dedicated branch. Could you please compile the code and try to import your data?
I took care of nothing showing the sensitive data (`secret`), but if you don't want to share the other info publicly just send me the output via e-mail :+1: 
You don't need to send me the whole output though, just 2/3 tokens before the crash and all the stuff that happens when the program crashes.
Thanks!

```
git clone https://github.com/paolostivanin/OTPClient -b debug-126
cd OTPClient
mkdir build && cd $_
cmake ..
make
./otpclient
```

**Comment by mannp** [comment] 2019-04-30 16:00
[INFO] Duplicate element not added
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Adding key 'type' and value 'TOTP'
===================================================================================================tmp_string was NULL. Details about the data are:
type: TOTP
label: 99
,issuer: ur
,digits: 6
,algo: SHA1
,period: 30

**Comment by paolostivanin** [comment] 2019-04-30 19:03
Interesting...what's the full label?

**Comment by paolostivanin** [comment] 2019-05-07 05:38
@mannp I tried to use all the possible combinations of letters, numbers and symbols, but couldn't reproduce the bug. I really need your original label + issuer in order to understand (I hope) what's wrong here :thinking:

**Comment by mannp** [comment] 2019-05-07 08:31
Hi @paolostivanin sorry for the delay.

The label in ondOTP is -> ur-99-v2:mannp@email.com bee
In OTPClient it is -> 'bee v2' and the issuer is 'ur'

**Comment by paolostivanin** [comment] 2019-05-07 11:32
Thanks @mannp ! I was able to partially reproduce the issue and I have already an idea on how to fix it.
I wasn't able to reproduce the crash part though :disappointed:  do you have any other "weird" label+issuer?

**Comment by mannp** [comment] 2019-05-07 12:51
Yes @paolostivanin I have some items incorrectly parsed? Well they seem to be anyway :)

For example where I have have a '-' in the username it has been incorrectly parsed and added to the issuer instead of it being part of the label; in fact it was the username for the 2fa.

**Comment by paolostivanin** [comment] 2019-05-07 13:17
@mannp the faulty code is here: https://github.com/paolostivanin/OTPClient/blob/c6ef5357b5fbf9bd37cfb609dc1bea2ebc3d6c54/src/andotp.c#L231
I guess that some times ago andOTP used to separate stuff with a dash. Now it respects the URI format and separates label and issuer using a colon.
I'll fix that asap and we'll see if that is enough to fix also the segfault...

**Comment by paolostivanin** [comment] 2019-05-07 13:33
@mannp can you please follow (again) the steps mentioned [here](https://github.com/paolostivanin/OTPClient/issues/126#issuecomment-487950902) and see if the fix works?

Thanks :+1:

**Comment by mannp** [comment] 2019-05-07 16:10
@paolostivanin 

After the very last item it gave me the following and wouldn't write the file;

> (OTPClient:15494): Gtk-WARNING **: 15:43:56.309: Failed to measure available space: Unhandled Apple File Control error (15)
> (OTPClient:15494): Gtk-WARNING **: 15:43:56.310: Failed to measure available space: Unhandled Apple File Control error (15)

Its arch linux so not sure why an apple error?
It went past the other previous items without issue though.

**Comment by paolostivanin** [comment] 2019-05-08 05:33
:astonished: now I'm confused! Let me google the error, I have absolutely no idea why this is happening...

**Comment by paolostivanin** [comment] 2019-05-08 05:51
@mannp I have updated the code on the debug branch. Could you please follow the steps mentioned before and paste here the output?
Thanks for your time and help :+1:

**Comment by mannp** [comment] 2019-05-08 16:06
Hi @paolostivanin so, ignore the apple error, it has gone away with your latest update. File on a local directory synced by nextcloud, so maybe that affected it somehow; anyway;

[1]    10604 segmentation fault (core dumped)  ./otpclient

It crashes on the following, but this time the label and issuer appear to have been parsed better, but shouldn't the full label be -> .ur-99-v2:mannp@email.com

> 
> The label in ondOTP is -> ur-99-v2:mannp@email.com bee
> In OTPClient it is -> 'ur-99-v2' and the issuer is 'bee'

**Comment by paolostivanin** [comment] 2019-05-09 12:47
Actually it's parsed correctly. It just a cosmetic thing that I should fix.
`label = issuer:accountname` or, when there's no issuer `label = accountname`.
Still, that's not the problem because when I tried with that data OTPClient didn't crash. So the issue must be elsewhere.
I really need a stripped down, cleaned up version of your database with which I can reproduce the issue. Could you please provide it to me? 
You should:
* export the **unencrypted** json
* strip it down, clean it up (change secret, email, etc)
* re-import the stuff in andOTP
* export the **encrypted** data
* make OTPClient crash. If not, try again.
Once you have a working version of the faulty database, please send it to me together with the decryption password :+1: 

Thanks a lot!!

**Comment by paolostivanin** [comment] 2019-05-22 10:03
Hey @mannp , any news? :smile:

**Comment by paolostivanin** [comment] 2019-06-11 08:38
should be fixed on latest master! Feel free to reopen it if that's not the case :+1:

**Comment by mannp** [comment] 2019-07-05 12:22
> Hey @mannp , any news? smile

Sorry @paolostivanin been on a months holiday! Will take another look, thanks.

**Comment by paolostivanin** [comment] 2019-07-11 07:42
@mannp sorry to hear that :(
You can use https://jsonformatter.curiousconcept.com/ to validate the json file, it always worked for me.
If you really want an editor then you can try atom+jsonlint.

**Comment by mannp** [comment] 2019-07-12 18:26
Hi @paolostivanin  thanks for the pointers, but nothing found as yet.

> 
>  JSON Lint report
> No errors were found!

Going to see if there is another app to import on my mac perhaps and then try and convert it back for my linux boxes..

**Comment by mannp** [comment] 2019-07-31 10:48
@paolostivanin So today there was an update of the Gnome Authenticator app and it successfully imported my json without issue (that is my tidied up json that wouldn't previously import on it or OTPClient)

The version is 3.32.2 as the previous version had the same error as OTPClient, but I have not had chance to track down the likely culprit that was fixed, to allow my import.

issue at the moment is that it will only allow me to export to unprotected JSON, so I am unable to import that into OTPClient.

> https://gitlab.gnome.org/World/Authenticator/-/releases

**Comment by paolostivanin** [comment] 2019-07-31 11:37
:thinking: I gave a quick look at the history but couldn't find much about changes in the import code.
I'm going to implement the unencrypted backup for v2 :+1: 
BTW, is there any way you can provide me with a reproducer? I really would like to fix this bug, but I need something I can work on first :(

**Comment by mannp** [comment] 2019-07-31 11:48
> thinking I gave a quick look at the history but couldn't find much about changes in the import code.
> I'm going to implement the unencrypted backup for v2 +1
> BTW, is there any way you can provide me with a reproducer? I really would like to fix this bug, but I need something I can work on first :(

I too just had a look and nothing was immediately obvious, looking also at the widget stuff as my error above reports that....

As I have not been able to isolate the issue, even after cutting the JSON down manually, without giving you the whole file I am not sure how I can give you that reproducer.

**Comment by paolostivanin** [comment] 2019-08-01 05:47
Looking at the error you had with Authenticator and [this commit](https://gitlab.gnome.org/World/Authenticator/commit/73de4274d1e86cdd3760d3b13d184bc111716a85), I'd say that it never had issue importing your json. You simply couldn't import it because of a small error in the import logic :thinking: 
I really wanna know what is happening here :tired_face:

**Comment by paolostivanin** [comment] 2019-08-01 06:07
Hi,
I've added some debugging output to help us understand where the issue is happening.
Could you please follow steps written here => https://github.com/paolostivanin/OTPClient/issues/126#issuecomment-487950902 and paste the output? thanks

**Comment by mannp** [comment] 2019-08-01 13:03
> Hi,
> I've added some debugging output to help us understand where the issue is happening.
> Could you please follow steps written here => [#126 (comment)](https://github.com/paolostivanin/OTPClient/issues/126#issuecomment-487950902) and paste the output? thanks

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> done prcessing element 72
=> updating and reloading db
[INFO]: before update_db on db-misc.c at line 81
[INFO]: after backup_db on db-misc.c at line 134
[1]    21231 segmentation fault (core dumped)  ./otpclient

**Comment by paolostivanin** [comment] 2019-08-01 13:15
ah ha! I've narrowed down the problem to 2 lines, let's check which one is the real culprit :sunglasses: 
Can you please update the branch `debug-126`, compile and execute the program and paste the output?
Thanks a lot :+1:

**Comment by mannp** [comment] 2019-08-01 13:24
> ah ha! I've narrowed down the problem to 2 lines, let's check which one is the real culprit sunglasses
> Can you please update the branch `debug-126`, compile and execute the program and paste the output?
> Thanks a lot +1

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
=> done prcessing element 72
=> updating and reloading db
[INFO]: before update_db on db-misc.c at line 81
[INFO]: after backup_db on db-misc.c at line 134
[INFO]: before g_slist_foreach
[INFO]: after g_slist_foreach
[1]    24818 segmentation fault (core dumped)  ./otpclient

**Comment by paolostivanin** [comment] 2019-08-01 14:41
I have updated the branch again. Could you please update it, recompile the program and then:
```
gdb ./otpclient
run
...make it crash...
bt
```
Please paste the output here :+1: 
Thanks!

**Comment by mannp** [comment] 2019-08-01 14:55
> I have updated the branch again. Could you please update it, recompile the program and then:
> 
> ```
> gdb ./otpclient
> run
> ...make it crash...
> bt
> ```
> 
> Please paste the output here +1
> Thanks!

=> done prcessing element 72
=> updating and reloading db
[INFO]: before update_db on db-misc.c at line 81
[INFO]: after backup_db on db-misc.c at line 134
[INFO]: before g_slist_foreach
[INFO]: after g_slist_foreach

Thread 1 "otpclient" received signal SIGSEGV, Segmentation fault.
0x00007ffff7483190 in ?? () from /usr/lib/libgcrypt.so.20
(gdb)

**Comment by paolostivanin** [comment] 2019-08-02 06:19
Dammit, I had the felling that the secure memory could have been the issue, and now I (almost) have the proof :cry: 
You said you're using arch, right? So `ulimit -l` should give you `unlimited` if I recall correctly from the time when I was using arch :thinking: 
If not, how much is the value? And how many tokens are u trying to import?

**Comment by paolostivanin** [comment] 2019-08-02 10:27
In the meanwhile, could you please update the branch `debug-126` (I just made some changes), recompile the software and try to import the encrypted backup again?
I'm not sure whether I'm hoping to hear a _yes_ or a _no_ xD

**Comment by mannp** [comment] 2019-08-02 10:28
> Dammit, I had the felling that the secure memory could have been the issue, and now I (almost) have the proof cry
> You said you're using arch, right? So `ulimit -l` should give you `unlimited` if I recall correctly from the time when I was using arch thinking
> If not, how much is the value? And how many tokens are u trying to import?

Its 1024 on desktop and laptop.

**Comment by mannp** [comment] 2019-08-02 11:53
> In the meanwhile, could you please update the branch `debug-126` (I just made some changes), recompile the software and try to import the encrypted backup again?
> I'm not sure whether I'm hoping to hear a _yes_ or a _no_ xD
=> done prcessing element 72
=> updating and reloading db
[INFO]: before update_db on db-misc.c at line 81
[INFO]: after backup_db on db-misc.c at line 134
[INFO]: before g_slist_foreach
[INFO]: after g_slist_foreach
[INFO] json_dumps done
[INFO]: before encrypt_db on db-misc.c at line 143
[INFO]: after encrypt_db on db-misc.c at line 143
[INFO]: before load_db on db-misc.c at line 119
[1]    8177 segmentation fault (core dumped)  ./otpclient

**Comment by paolostivanin** [comment] 2019-08-06 07:20
good news! I was able to reproduce the bug and I found a fix for it :D 

@mannp please update the branch, recompile the program and try to import the data again :+1:

**Comment by mannp** [comment] 2019-08-06 10:41
> good news! I was able to reproduce the bug and I found a fix for it :D
> 
> @mannp please update the branch, recompile the program and try to import the data again +1

Excellent!

@paolostivanin I have updated and used a fresh export from andOTP and have the following output;

[INFO] Duplicate element not added
=> done prcessing element 72
=> updating and reloading db
[INFO]: before update_db on db-misc.c at line 81
[INFO]: after backup_db on db-misc.c at line 134
[INFO]: before g_slist_foreach
[ERROR] couldn't add value to array
[ERROR] couldn't add value to array
[INFO]: after g_slist_foreach
couldn't dump json data
[INFO]: before encrypt_db on db-misc.c at line 143
[1]    5128 segmentation fault (core dumped)  ./otpclient

There are 73 items so it looks like it is failing on the final one?

**Comment by paolostivanin** [comment] 2019-08-06 11:36
Apparently, this bug seems to be caused by multiple things.
One was the secure memory allocation (fixed, I tested it by importing 150 tokens) and the second one seems to be related to the json file :thinking:
The program cannot add some tokens (not a problem, they are just ignored) and, for some reasons, couldn't parse the json from memory.
Problem is that (for now) I can't reproduce the second part :disappointed:

**Comment by paolostivanin** [comment] 2019-08-06 12:25
I have pushed some other changes (using custom func instead of gcrypt to handle json stuff).
Could you please do the usual (pull, recompile, etc)? :+1: 
Thanks @mannp

**Comment by mannp** [comment] 2019-08-06 12:59
[1]    14218 segmentation fault (core dumped)  ./otpclient

with gdb

Thread 1 "otpclient" received signal SIGSEGV, Segmentation fault.
0x00007ffff74b0f0b in ?? () from /usr/lib/libgcrypt.so.20

**Comment by paolostivanin** [comment] 2019-08-06 13:45
Back to sqr(1) until I find a way to reproduce the bug :disappointed:

**Comment by mannp** [comment] 2019-08-06 13:49
> Back to sqr(1) until I find a way to reproduce the bug disappointed

Thought so, but thanks for your perseverance!

**Comment by paolostivanin** [comment] 2019-08-06 13:57
the only good bug is a dead bug (cit.) :smile:

**Comment by mannp** [comment] 2019-08-06 14:03
> the only good bug is a dead bug (cit.) smile

Lol, very true :)

**Comment by paolostivanin** [comment] 2019-11-13 15:04
I've added plaintext support and, moreover, some other stuff changed in the encryption format.
I'll close this given that with v2 there will be a why to workaround this not-so-easy-to-reproduce issue :+1:

**Closed by paolostivanin** 2019-11-13 15:04 UTC
Labels: Status: Done, Type: Bug

**Comment by mannp** [comment] 2019-11-13 16:36
Sure, i'll give v2 a try and let you know, once its got an initial release :)
