### ISSUE TITLE
OTP Value matches incorrect entries after sorting by account or issuer.

### ISSUE THREAD

**Issue by Baa14453** [paolostivanin/OTPClient#181] opened 2020-06-18 08:34 UTC
### Issue:
After sorting the entries in OTP Client by 'Account' or 'Issuer', the next generated codes will be for the wrong entry.

### Steps to recreate:
1. Click onto 'Account', or 'Issuer'
2. Generate a new code, it will be wrong.

### Workaround
1. Open the Options and click 'Reset column sorting'
2. Restart the program
3. Generate a new code, it will be correct.

Tested on Ubuntu 20.04 using the apt package, version 2.3.0.

**Comment by paolostivanin** [comment] 2020-06-18 08:41
Are you using Flatpak, source, or deb package?

**Comment by Baa14453** [comment] 2020-06-18 08:42
The issue started on the deb package on version 2.3.0
I compiled 2.3.1 from source yesterday but the issue persists

**Comment by Baa14453** [comment] 2020-06-18 09:36
Just compiled v2.2.1 to be sure but no change

**Comment by paolostivanin** [comment] 2020-06-18 09:37
Weird, really weird :thinking: I'm installing Ubuntu to check with my data

**Comment by paolostivanin** [comment] 2020-06-18 10:18
Nope, I was able to import my andOTP backup into OTPClient 2.3.0 on Ubuntu 20.04. All worked fine and the codes were good :thinking:

**Comment by Baa14453** [comment] 2020-06-18 10:29
Any ideas what might affect it? maybe some system configuration or something, what affects the code generation?

**Comment by paolostivanin** [comment] 2020-06-18 14:21
There are other people facing similar issues (see #179), but I haven't been able to debug this problem because I can't reproduce it :disappointed: 
There's no config affecting the code generation, once the data is stored inside the db, only that data is used. 
The config is just for some UI stuff.
The only thing that can affect the code is the system clock, because TOTP are using the system time to generate a code.
The data inside the database is OK and not corrupted if you were able to export it and use it on your phone, so (unfortunately) this is not actually helping me in narrowing down the issue...

**Comment by paolostivanin** [comment] 2020-06-18 14:25
Could you try to:
* create a VM with whatever linux distro
* install otpclient
* copy over your database to the vm
* restore that database and see if the codes work?

**Comment by Baa14453** [comment] 2020-06-21 13:16
It works fine inside my VM, exact same OS

**Comment by Baa14453** [comment] 2020-06-21 13:34
ok I've just been messing with it
It's something to do with re-ordering the entries in the GUI, the codes matched up to the wrong entries
I'll do more testing later

**Comment by Baa14453** [comment] 2020-06-21 16:32
Resetting the column order and restarting the program fixed the bug

**Comment by Baa14453** [comment] 2020-06-21 16:38
I can re-create the bug by sorting by issuer or account, the next code generated will be wrong.
This is on 2.3.0

**Comment by paolostivanin** [comment] 2020-06-22 07:23
Thanks for your investigation :D this is very helpful, now I'll finally be able to fix this issue!!

**Comment by paolostivanin** [comment] 2020-06-25 11:41
This particular issue is now fixed.
Now I'm dealing with another annoying bug where entries get duplicated when sorted :roll_eyes:

**Comment by precla** [comment] 2020-06-25 19:53
> This particular issue is now fixed on the branch fix-181.
> Now I'm dealing with another annoying bug where entries get duplicated when sorted roll_eyes

Try 'Stalin sort' :)

**Comment by mcmurphy8097234789** [comment] 2020-07-23 08:46
When is the fix coming downstream? The latest release is 2.3.1 which was released in May

**Comment by paolostivanin** [comment] 2020-07-23 08:50
sorry, was on vacation! I'll release it later today :+1:

**Closed** 2020-07-23 09:03 UTC
Labels: Status: Done, Type: Bug

**Comment by h1z1** [comment] 2021-01-25 10:06
OMG.. I've spent _hours_ trying to figure out why the token being generated wasn't correct / being accepted.  This seriously needs to be pinned to warn users.
