### ISSUE TITLE
[andOTP] cannot import, file corrupted or password wrong

### ISSUE THREAD

**Issue by SuperSandro2000** [paolostivanin/OTPClient#162] opened 2019-12-24 15:41 UTC
I wanted to import an encrypted andOTP backup and I get this error:
![image](https://user-images.githubusercontent.com/7258858/71418567-5ead6700-266b-11ea-9f4b-75d4dc4508b7.png)

I copied the file from one of my backups and from my phone directly and the password from my password manager. I get no other error in the console. It could be that the password it the long as I have a 100+ char one.

Importing plain text works like a charm.

**Comment by calisro** [comment] 2019-12-25 17:02
Doesn't work for me plain or encrypted.  I think the new andotp for android uses RSA?

**Comment by paolostivanin** [comment] 2019-12-29 17:13
@SuperSandro2000 are u using the latest version? (should be 0.6.3)
I'm asking because andOTP changed the encryption algo some time ago, so now OTPClient only supports the latest version.

@calisro what error are u getting? It's weird that both plain and encrypted do not work

**Comment by SuperSandro2000** [comment] 2019-12-30 00:25
> @SuperSandro2000 are u using the latest version? (should be 0.6.3)

Yes, 0.6.3.1.

**Comment by paolostivanin** [comment] 2020-01-15 09:59
For me it works. I can import both encrypted and plain backup :thinking: 
I'd need you to provide me with a sample backup file that triggers the issue, because I can't reproduce it :(

**Comment by SuperSandro2000** [comment] 2020-01-15 18:12
Did you try it with BattelNet Authenticator and Twitch included?

**Comment by paolostivanin** [comment] 2020-01-16 07:44
Nope because I don't have either. What's so particular about them? :thinking:

**Comment by SuperSandro2000** [comment] 2020-01-16 10:06
They have a different length. Battle.net is 8 numbers and twitch 7. Also the timeouts vary. See https://github.com/andOTP/andOTP/wiki/Shared-secrets

**Comment by paolostivanin** [comment] 2020-01-17 08:26
I was actually able to import andOTP data with a battle net account in it :thinking:  will try with twitch, but it would be faster if you could send me a reproducer :+1:

**Comment by hwoarang** [comment] 2020-03-08 09:09
I do have the same problem using 0.6.3.1 and otpclient 2.1.0. The strange thing is that the application is asking for 'decryption password' even when I try to import a plain json file.

**Comment by paolostivanin** [comment] 2020-03-09 08:53
@hwoarang glad you solved :) but good point, that's currently not very clear. I'll fix it with the next release :+1:

**Comment by paolostivanin** [comment] 2020-04-09 14:17
I'm closing this until someone is able to provide me with a reproducer!

**Comment by SuperSandro2000** [comment] 2020-04-11 06:28
When I import the backup in plain text nothing crashes but when I import the encrypted one it has an error. I am not sure how to strip private information or edit the encrypted backup so I sadly can't provide you with a working example.

**Comment by paolostivanin** [comment] 2020-04-11 10:04
@SuperSandro2000 if you're willing to help me debug this issue, I can work on it, no problem :) I really would like to find and fix this bug.
What about we do the following
1. I will develop a cli that will export your data in the andotp encrypted format
2. the export operation will replace only the **secret** with some random chars
3. all the other fields will remain the same
4. you send me via email the exported backup
If you agree with that, I'll proceed with developing a simple CLI for that. What do you think?

**Comment by SuperSandro2000** [comment] 2020-04-11 22:41
I did some further testing and it has nothing todo with the content of the backup. My password is just to long and somewhere it is overflowing I guess.

Here is a dummy backup with the password ``111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111``
[otp_accounts.json.aes.zip](https://github.com/paolostivanin/OTPClient/files/4465577/otp_accounts.json.aes.zip)

**Comment by paolostivanin** [comment] 2020-04-12 15:59
nice, thanks! Imma look into it asap :)

**Comment by paolostivanin** [comment] 2020-04-13 07:23
Using a python script:
```
Iterations: 3210
Salt: (12) 0xff6e45cdd4e25fbbdbb0f19d
Pbkdf2 key: (32) 0x31836a3c670ddda59c65e43e34a67bc2ee314bb21d2c159bf8ca9168489ddc67
Input bytes: % (199) 0x1c220cf9a608217ecb82ab30fc7bde657d599121ddd7d67abe6113c32ef74215130117ae4fa20e1e206a2aa14ed44d8e58dcf09ed39d03144d0e7d3cd8cce0f3a8b8dab0897f9c3a5e8e51892f007f73c7614036d7f8d2471984a531854bd6b6881d9e64485b1b7bdb9626a9824ce4d3d783712c351c98285a5e701a12a89818deed3adbfc650b1cb7bb6abdd9c272039e4b912bae83d876cfcf6146d1684c562f0b53ab602630f1afe943016b9fbc6def7c569d1e984f747087753ee3b8b7cfb979b695335771
IV: (12) 0x1c220cf9a608217ecb82ab30
Crypttext: (171) 0xfc7bde657d599121ddd7d67abe6113c32ef74215130117ae4fa20e1e206a2aa14ed44d8e58dcf09ed39d03144d0e7d3cd8cce0f3a8b8dab0897f9c3a5e8e51892f007f73c7614036d7f8d2471984a531854bd6b6881d9e64485b1b7bdb9626a9824ce4d3d783712c351c98285a5e701a12a89818deed3adbfc650b1cb7bb6abdd9c272039e4b912bae83d876cfcf6146d1684c562f0b53ab602630f1afe943016b9fbc6def7c569d1e984f
Auth tag: (16) 0x747087753ee3b8b7cfb979b695335771
Decrypted data: (171) 0x5b7b22736563726574223a22222c22697373756572223a22222c226c6162656c223a22222c22646967697473223a362c2274797065223a22544f5450222c22616c676f726974686d223a2253484131222c227468756d626e61696c223a2244656661756c74222c226c6173745f75736564223a313538363634343035333332362c22757365645f6672657175656e6379223a312c22706572696f64223a33302c2274616773223a5b5d7d5d
```

with otpclient:
```
Iterations: 3210
SALT: ff6e45cdd4e25fbbdbb0f19d
PBKDF2 Key: 20d5368b3af99bb2f3eb40a3d35d3a94e9ea0c74d74636457a0f8b3c967
IV: 1c22cf9a68217ecb82ab30
Auth tag: 747087753ee3b8b7cfb979b695335771

```

Some weird thing is happening when otpclient derives a long password...

**Comment by paolostivanin** [comment] 2020-04-13 07:46
Found the error and fixed it :) thanks a lot @SuperSandro2000 for your help!
It was weird because, for some reasons, this bug was happening only with very long backup password.
But now it's gone. Forever (hopefully). :partying_face:

**Closed** 2020-04-13 07:45 UTC
Labels: Status: In Progress

**Comment by paolostivanin** [comment] 2020-04-13 07:47
If you confirm me it's fixed, I'll publish a new release :)

**Comment by SuperSandro2000** [comment] 2020-04-13 09:39
Worked with the example and my real backup! Thank you very much!

**Comment by paolostivanin** [comment] 2020-04-13 09:46
Niceeeee :D 
I'll prepare a release later today!
