### ISSUE TITLE
Import andOTP Steam secret type

### ISSUE THREAD

**Issue by theit8514** [paolostivanin/OTPClient#119] opened 2019-02-24 18:05 UTC
When exporting Steam secret from andOTP, the type is exported as "STEAM" and not "TOTP". OTPClient gives this error when trying to import:

"An error occurred while importing, so nothing has been added to the database.
The error is: otp type is neither TOTP nor HOTP"

Example of the JSON from andOTP:
```
   {
      "thumbnail" : "Steam",
      "secret" : "xxxx",
      "digits" : 5,
      "tags" : [],
      "last_used" : nnnn,
      "label" : "Steam",
      "algorithm" : "SHA1",
      "type" : "STEAM"
   },
```

**Comment by paolostivanin** [comment] 2019-02-24 18:26
Thanks for reporting the issue!

I'll fix this with v1.4.0 :smile:

**Comment by paolostivanin** [comment] 2019-02-26 19:53
Hi @theit8514 ! Could you please test the commit I just pushed into develop-1.4.0 ?
I don't have a Steam account, so I can't verify the issue is really fixed.

Thanks a lot!

**Comment by theit8514** [comment] 2019-02-28 02:25
My andOTP export is now importing correctly but the line item for Steam is not usable. Clicking the line does not show a token in the GUI and shows the following line in the console, which I assume means that it tried to copy a null value.

(OTPClient:21423): Gtk-CRITICAL **: 21:18:34.405: gtk_clipboard_set_text: assertion 'text != NULL' failed

If I take the key from the decrypted json file and add it manually to OTPClient, the token does generate properly and the token is valid when I log into Steam. There must be an issue with the import.

**Comment by paolostivanin** [comment] 2019-02-28 07:05
Mmm, interesting! I'll look into it this evening!

Thanks for your help :+1:

**Comment by paolostivanin** [comment] 2019-02-28 14:57
@theit8514 now the issue should be fixed. Could you please try again now with latest commit from develop-1.4.0 branch?

**Closed** 2019-03-04 06:51 UTC
Labels: Status: In Progress, Type: Bug
