### ISSUE TITLE
Incorrect generated codes for PayPal from imported andOTP encrypted JSON file

### ISSUE THREAD

**Issue by modestderp** [paolostivanin/OTPClient#179] opened 2020-06-06 03:27 UTC
Pretty much what the title says.

I imported a encrypted JSON file from andOTP and discovered the OTP codes for PayPal is incorrect. This did not happen before when I used a previous version.

I am currently using the latest version from Flathub: 2.3.0

**Comment by precla** [comment] 2020-06-07 21:07
Can confirm. Just imported andOTP backup into OTPClient. None of the generated keys work. Checked clock on phone, time and date is fine.
Using OTPClient 2.3.1
andOTP backup is encrypted

**Comment by paolostivanin** [comment] 2020-06-08 09:42
If installed from the distro's repo, then it works. So it must be something related to flatpak... :thinking: 
I'll look into it

**Comment by precla** [comment] 2020-06-08 14:31
Installed via arch repo, no flatpak version.

**Comment by paolostivanin** [comment] 2020-06-08 15:05
Same is happening here (openSUSE Tumbleweed) after the GCC 10 update. I guess also Arch is using GCC10, so it must something related to it.
That's gonna be a pain to debug :disappointed:

**Comment by alanorth** [comment] 2020-06-09 07:58
@precla I just [posted an updated PKGBUILD for the Arch AUR version](https://aur.archlinux.org/packages/otpclient/#news) and my codes imported from another Android 2FA client (Aegis) work now. Try to build using my updated PKGBUILD and see if it works for you.

**Comment by paolostivanin** [comment] 2020-06-09 14:42
@precla I'm also using andOTP, and I was able to import the encrypted backup :thinking: 
Can you pls execute `otpclient` from terminal and post the output? Maybe there's something useful there...

@modestderp I'm investigating the flatpak bug, but (for now) I can't really say what's wrong there and why it's generating a different code :exploding_head:

**Comment by paolostivanin** [comment] 2020-06-22 07:24
@precla @modestderp did you by chance sort the entries by label/issuer?

**Comment by precla** [comment] 2020-06-22 18:20
@paolostivanin treid wit sorting by account and issuer, same result. I reimported my andOTP backup again and still the same problem

**Comment by Baa14453** [comment] 2020-06-24 18:46
@precla go to Options and Reset Column Sorting
Then restart it and try again
![image](https://user-images.githubusercontent.com/9057997/85614930-65855880-b653-11ea-8ed7-c962d9e00e9a.png)

**Comment by precla** [comment] 2020-06-24 19:06
@Baa14453 Thanks! That did it and login works now again!

**Comment by paolostivanin** [comment] 2020-06-25 07:33
I'm already working on a fix, thanks to @Baa14453 who found out how to reproduce the issue :)

**Comment by paolostivanin** [comment] 2020-06-25 11:36
I'm closing this as the issue is now tracked in #181

**Closed by paolostivanin** 2020-06-25 11:36 UTC
Labels: Status: In Progress, Type: Bug
